package cloudtasks

import (
	"encoding/json"
	"fmt"
)

type Task struct {
	key     string // key we are invoking
	name    string // name of the task, autogenerated if empty
	payload []byte // body of the request

	// Read only. Number of previous retries.
	Retries int64
}

func (task *Task) Name() string {
	return task.name
}

func (task *Task) Read(dest interface{}) error {
	if err := json.Unmarshal(task.payload, dest); err != nil {
		return fmt.Errorf("cloudtasks: cannot read task payload: %w", err)
	}
	return nil
}

type TaskOption func(task *Task)

func WithName(name string) TaskOption {
	return func(task *Task) {
		task.name = name
	}
}
